---
abstract: 'Test Module for Alien::Base'
author:
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Joel A. Berger <joel.a.berger@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  ExtUtils::CBuilder: '0'
  Test::More: '0'
configure_requires:
  Alien::Base: '0.016'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Alien-DontPanic
provides:
  Acme::Alien::DontPanic:
    file: lib/Acme/Alien/DontPanic.pm
    version: '0.021'
requires:
  Alien::Base: '0.016'
  File::ShareDir: '1.00'
  perl: '5.008001'
resources:
  MailingList: https://groups.google.com/forum/#!forum/perl5-alien
  bugtracker: http://github.com/Perl5-Alien/Alien-Base-Extras/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Perl5-Alien/Alien-Base-Extras
version: '0.021'
